### ISSUE TITLE
Certain diagram types are not working on M1 Macs

### ISSUE THREAD

**Issue by malclear** [esteinberg/plantuml4idea#365] opened 2022-10-14 21:42 UTC
I've recently installed the plugin in Rider on my Mac M1 (ARM64) machine. I also installed Graphviz via `brew install graphviz`. Now, only the Sequence and Activity diagrams are working. The 6 other file types I tested all returned a message stating: 
![image](https://user-images.githubusercontent.com/11647697/195946938-1040c54a-74aa-4622-95c5-805df6319bd3.png)

I did find the jar file related to PlantUml in the following directory and ran the suggested command regarding "testdot":
`/Users/[ *** my user name ***]/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/222.4167.23/Rider.app.plugins/plantuml4idea/lib`. 
I got the following result: 
![image](https://user-images.githubusercontent.com/11647697/195947209-48bb0db9-a9f2-4906-bbc3-e634cc8d3c50.png)

I've tested this on three different Mac M1s (but nothing else) and got the same results each time.

**Comment by malclear** [comment] 2022-10-14 21:48
A workaround/solution to this was found by my very smart friend and co-worker, @jblackburn21. The solution involves adding a sym link from the Dot executable path listed in the image above to the correct location. 

`cd /opt
sudo mkdir -p local/bin
sudo ln -s /opt/homebrew/bin/dot /opt/local/bin/dot`

**Comment by malclear** [comment] 2022-10-17 00:58
Reopening as I realized the previous comment was more workaround than solution.

**Comment by jblackburn21** [comment] 2022-10-17 13:44
This is a duplicate of #330 but with an alternative solution. The default paths for plantuml look for `/usr/local/bin/dot`, `/usr/bin/dot`, or the `GRAPHVIZ_DOT` env var. Any of these can be restored since the graphviz brew package installs to `/opt/homebrew/bin/dot`.

**Comment by izmaylovdev** [comment] 2023-02-24 08:49
I have the same issue, I have set `GRAPHVIZ_DOT` variable and looks like `testdot` works fine:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/14952947/221133669-44be9cef-6e04-4d6e-9d95-3ecadb01ba1f.png">
but when I try to create diagram I get: 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/14952947/221134081-c3a79d71-0d56-49d7-8757-bb05dc25e7cd.png">
variable setup: 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/14952947/221134153-a40d3a22-badf-463f-83a9-494aa7d6b7d0.png">

**Comment by krasa** [comment] 2023-02-24 09:12
related #379

Does it work from the command line?

**Comment by izmaylovdev** [comment] 2023-02-25 22:10
@krasa yes, it works
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/14952947/221381755-8a28ff4a-67fb-497e-9154-dc5f31f08299.png">

**Comment by pmverma** [comment] 2023-07-21 05:16
I am having the same problem as well with homebrew installed graphvis.
Everything is installed and set up as expected, still not working.

**Comment by krasa** [comment] 2023-08-28 20:35
Lets continue this in #379

**Closed by krasa** 2023-08-28 20:35 UTC
